[package]
name = "file-organizer"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
dirs = "6.0.0"
rfd = "0.15.3"
indicatif = "0.17.8"
colored = "2.1.0"
rayon = "1.10.0"
dialoguer = "0.11.0"
walkdir = "2.5.0"
