name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --current --strip header
        env:
          OUTPUT: CHANGELOG.md
      - name: Upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: CHANGELOG.md

  windows:
    needs: changelog
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install WiX
        run: |
          curl -LO https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
          7z x wix311-binaries.zip -o"$env:WIX"
      - name: Build MSI
        run: |
          cargo install cargo-wix
          cargo wix
      - name: Upload MSI
        uses: actions/upload-artifact@v2
        with:
          name: windows-msi
          path: target/wix/*.msi

  linux:
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build DEB
        run: |
          cargo install cargo-deb
          cargo deb
      - name: Upload DEB
        uses: actions/upload-artifact@v2
        with:
          name: linux-deb
          path: target/debian/*.deb

  macos:
    needs: changelog
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build DMG
        run: |
          cargo install cargo-bundle
          cargo bundle --release      - name: Upload DMG
        uses: actions/upload-artifact@v2
        with:
          name: macos-dmg
          path: target/release/bundle/osx/*.app

  create-release:
    needs: [changelog, windows, linux, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download all artifacts
        uses: actions/download-artifact@v2
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-msi/*.msi
            linux-deb/*.deb
            macos-dmg/*.app
          body_path: changelog/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
