name: Create Release

on:
  workflow_run:
    workflows: ['Release Windows Build', 'Release Linux Build', 'Release macOS Build']
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    # Only run when all builds are complete
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      !github.event.workflow.processed
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get the tag that triggered the release
      - name: Get tag
        id: tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Generate changelog
        uses: orhun/git-cliff-action@v2
        with:
          config: cliff.toml
          args: --current --strip header
        env:
          OUTPUT: CHANGELOG.md

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            artifacts/windows-msi/*.msi
            artifacts/linux-deb/*.deb
            artifacts/macos-dmg/*.app
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}